<?php

namespace AppBundle\Repository\Users;
use AppBundle\Repository\UserRepository;
use AppBundle\Entity\Users\Employee;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends UserRepository
{
  public function all() {
    // $query = $this->getEntityManager()
    // ->createQuery(
    //   'SELECT p
    //   FROM AppBundle\Entity\Users\Employee p
    //   WHERE p.role = :role'
    // )->setParameter('role', "employee");

    return $this->findAll();
  }
}
