<?php

namespace AppBundle\Repository\Users;
use AppBundle\Repository\UserRepository;
/**
 * ManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerRepository extends UserRepository
{
}
